### ISSUE TITLE
High: Unable to leave a dialog 

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#12] opened 2017-02-13 15:44 UTC
In the following scenario, users are unable to leave a conversation:

1. Tapping the "Leave conversation" on the first dialog (either by swiping right on the dialog list or from the Settings screen) 
2. Hitting the iOS Home button  
3. Re-opening the app

After step 1, the dialog disappears but in step 3, the dialog re-appears and in a broken state (unable to send messages - the users get failed message indication, dialog is not named, etc.).

**Comment by laeroah** [comment] 2017-02-14 04:54
@hagitmer I can't reproduce this in the sample app at all. 
From what you describe, it seems the user did exit from the conversation but somehow the local cache didn't get cleared. However, leaving a conversation is tested repeatedly everyday here, so I am sure what went wrong yet.
Please confirm if this problem still exists in the latest version of the SDK, and if it does, I might have to speak to your team and try gather some more information.

**Comment by hagitmer** [comment] 2017-02-16 01:01
Will check again, thanks @laeroah

**Comment by dfredmen** [comment] 2017-02-16 21:57
I cannot reproduce either (this is Dane)

**Comment by laeroah** [comment] 2017-02-16 22:31
close it for now. We can re-open this if it ever get spotted again.

**Closed as completed by laeroah** 2017-02-16 22:31 UTC
Labels: cannot reproduce
