### ISSUE TITLE
High: Not seeing message title for 1-1 message after tapping push notification

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#9] opened 2017-02-01 15:46 UTC
Steps to reproduce:

1. Device A is logged in, with the app running in the background.
2. Device B creates a brand new direct message with the user on Device A.
3. Device B sends a message.
4. Device A gets a push notification from GC (you can be in the lock screen or home screen, as long as the app isn't open)
5. Device A's user taps the push notification. The message opens, there is content in the chat view however the title is showing "unknown" instead of the user's name. 

Note: if user A navigates back to the convo list and then back to the DM, the title is showing user B's name as expected.

**Comment by hagitmer** [comment] 2017-02-09 02:55
Also happened in Android: https://github.com/Hacknocraft/AppFriendsAndroidCore/issues/22

**Comment by laeroah** [comment] 2017-02-09 03:46
@hagitmer The problem has the cause as on Android. The push is clicked before the actual first message of the dialog reached the app. We solved it on Android but a little awkwardly. We have a plan to do a more elegant fix to solve this issue on both platforms, but it will take some time.

In the meanwhile, on iOS, what you can do is, after the app receives the push notification, and before you enter the dialog, please use
`if let dialog = CoreStoreManager.store()?.fetchOne(From(HCChatDialog.self), Where("dialogID", isEqualTo:_dialogID))` to check if a dialog with the ID exists locally. 
If it does exist, enter the dialog normally. 
Else, use `DialogsManager.fetchDialogInfo` to fetch the dialog, and,
If it returns without error, you can proceed entering the dialog. 
Else, use `AppFriendsUserManager.fetchUserInfo` to fetch the user data
if it returns success, use `DialogsManager.initializeDialog` with the `[userid]` and `HCSDKConstants.kMessageTypeIndividual`

What's happening here, is that we:
1. see if dialog exists locally, if it does, we can enter the dialog immediately, if not
2. fetch dialog from the server, however, if it's an 1 on 1 chat, dialog info is not on the server, so
3. fetch the user from the server
4. initiate the dialog passing the user id and definite the dialog type to be individual
If you know the dialogID is an user id, then you can simplify the process.

I understand it looks very hackish, but I think the logic is easy to understand, and is better than rushing out a patch. We will definitely clean this up and you could remove all these code soon.

**Comment by hagitmer** [comment] 2017-02-09 04:24
Thanks @laeroah. When do you think you can provide the elegant solution? We might be able to wait for it. Thanks.

**Comment by laeroah** [comment] 2017-02-09 05:05
we can prioritize this fix and make a release by next Thursday.

**Comment by hagitmer** [comment] 2017-02-10 16:04
Sounds good, thanks.

**Comment by laeroah** [comment] 2017-02-10 16:24
yeah, it's the same issue, which will be fixed as well.

**Closed as completed** 2017-02-17 05:16 UTC
Labels: released
